package model;

/**
 * Game model class
 * Represent a video game stored in the system.
 * This class is used to transfer data between the application and the database.
 */
public class Game {
    private int id;
    private String title;
    private String platform;
    private String genre;
    private String status;
    private double rating;
    private String notes;
    
    // No parameter default Constructor
    public Game() {
        
    }
    // Constructor with Parameters. This is used to create a new game (ID is auto generated by the database).
    public Game(String title, String platform, String genre, 
            String status, double rating, String notes) {
        
        this.title = title;
        this.platform = platform;
        this.genre = genre;
        this.status = status;
        this.rating = rating;
        this.notes = notes;
    }
    
    // Getters methods. These are used to retrieve the game information.
    public int getId() {
        return id;
    }
    
    public String getTitle() {
        return title;
    }
    
    public String getPlatform() {
        return platform;
    }
    
    public String getGenre() {
        return genre;
    }
    
    public String getStatus() {
        return status;
    }
    
    public double getRating() {
        return rating;
    }
    
    public String getNotes() {
        return notes;
    }
    
    // Setters methods. These are used to update game information
    public void setId(int id) {
        this.id = id;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    public void setPlatform(String platform) {
        this.platform = platform;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public void setRating(double rating) {
        this.rating = rating;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    @Override
    public String toString() {
        return "Game{" + "title=" + title + ", platform=" + platform + ", genre=" + genre + ", status=" + status + ", rating=" + rating + ", notes=" + notes + '}';
    }
    
}
